### ISSUE TITLE
Fan plots look wrong

### ISSUE THREAD

**Issue by richardreeve** [richardreeve/Phylo.jl#19]
Not sure what's going on here, but fan plots are not working correctly, even though dendrogram plots work fine. I can't see an obvious difference between the two recipes, but there's obviously something in there...

**Comment by mkborregaard** [comment]
Oh, never saw this - can you give an MWE?

**Comment by richardreeve** [comment]
Will try to remember what was going on!

**Comment by mkborregaard** [comment]
I think this has to do with the ordering. That you can't guarantee the nodes come in some order. Didn't we discuss this before?
