### ISSUE TITLE
Switch to Project.toml?

### ISSUE THREAD

**Issue by asinghvi17** [richardreeve/Phylo.jl#26]
This is holding back some packages from Requires 1.0.

**Comment by mkborregaard** [comment]
@richardreeve time to merge https://github.com/richardreeve/Phylo.jl/pull/20 ?

**Comment by richardreeve** [comment]
Hi @asinghvi17. Yes, sorry about this. I've got the whole of tomorrow free of covid stuff, and I'll try to merge #20 and #25 then and sort all of this out.

**Comment by richardreeve** [comment]
This is fixed now in v0.4.0. I can't actually get my Diversity.jl package that depends on it to update because of some dependency hell, but we can't win every time I guess...
