### ISSUE TITLE
fix TypeError in case LinkBranch has no length information

### ISSUE THREAD

**Issue by dies-und-lenes** [richardreeve/Phylo.jl#33]
Hi, 

I think it should be a `ismissing()` instead of `isnan()` [here](https://github.com/richardreeve/Phylo.jl/blob/0e0234d448efd0d75c841733cb4b61f3a90120c4/src/LinkTree.jl#L481) and [here](https://github.com/richardreeve/Phylo.jl/blob/0e0234d448efd0d75c841733cb4b61f3a90120c4/src/LinkTree.jl#L485),  otherwise there will be a "non-boolean (Missing) used in boolean context" TypeError.

Example: 
```
> mytree = parsenewick("((A,B),C);")
> mytree.branches[1]
```

Thank you for the great package!

**Comment by richardreeve** [comment]
Thanks @dies-und-lenes - sorry for the delay in picking up on this, I've been really busy!
