### ISSUE TITLE
newick parser

### ISSUE THREAD

**Issue by mkborregaard** [richardreeve/Phylo.jl#4]
Hi,
is a newick parser on the road map, or do you intend to rely on the R interface for now?

Thanks!

**Comment by richardreeve** [comment]
Hah. I'd certainly like to have a parser, but at the moment I'm focussed on debugging the existing code (I'm finding plenty of bugs I'm afraid) and then on making it as easy as possible to generate, edit and annotate trees first.

Once I've got that sorted, I'd be keen to work on a parser, but my recollection from writing one for ruby many years ago (hint: mine wasn't great!) is that to get it to work well you need all of that working first. Anyway, in the meanwhile I think it's reasonable to use existing (R) parsers first, and once I can do translations of those to Julia well it'll be a lot easier to write the parser itself in Julia...

**Comment by mkborregaard** [comment]
Cool, thanks. I can certainly understand that set of priorities. I am just asking because no julia packages to my knowledge currently have a newick parser (Bio had one, but it was dropped because it was built on commercial open-source software that discontinued its julia support) - and it seems to be the most requested phylogeny-related feature in Julia :-)
Until then, it's certainly a nice workaround to have the rcopy functionality.

**Comment by richardreeve** [comment]
BTW on master `@rget` now (hopefully!) works to translate any rooted S3 `phylo` binary tree from R to julia as a `NamedTree`, and `@rput` will translate the structure of any `BinaryTree` (including `NamedTree`) to R as a `phylo` object (though not the metadata), so things are progressing...

**Comment by richardreeve** [comment]
Okay, I have an incredibly hacky parser for newick trees in Julia in #5 that uses the Julia tokenizer. Unfortunately the BioJulia Automa.jl is far too limited to be able to parse a file format like this, but my appalling code seems to work for the time being!

It seems to work okay with the basic newick tree examples online, and the `(...);` bit of a .trees file output from BEAST (I think the whole thing is in NEXUS format?). I don't actually use this stuff, so if anyone's really interested, can they check it out?

Note, as the whole package at the moment, it only works with binary trees...

**Comment by richardreeve** [comment]
Okay, it passes all of my tests, and so I'm going to merge it...

**Comment by mkborregaard** [comment]
Thanks so much for moving so fast on this, Richard! I am on holidays for a month but will look very much forward to playing with this when I get back.

**Comment by richardreeve** [comment]
Great, speak to you when you get back.
