### ISSUE TITLE
Plot tree doesn't show the tips

### ISSUE THREAD

**Issue by diegozea** [richardreeve/Phylo.jl#53]
Hi! 

We have just found a problem with the Plot recipe for Phylo's trees. The plots do not show the tips, as shown in https://github.com/EcoJulia/NCBITaxonomy.jl/issues/32. The code here can be used as an example of the problem: http://docs.ecojulia.org/NCBITaxonomy.jl/dev/phylo/ The misbehaviour can be related to changes in Plots. 

I really appreciate any help you can provide.

**Comment by richardreeve** [comment]
@mkborregaard Do you have any thoughts about how to fix this problem with plotting no longer displaying tips? Or are we misunderstanding how it works?

**Comment by mkborregaard** [comment]
This is a loss-of-function bug I discovered myself recently and failed to open an issue. I've got no really good ideas what the issue is and suspect it may be Plots side

**Comment by richardreeve** [comment]
@diegozea Sorry to do this to you, but it looks like if you have a bit of time you could try over on [Plots.jl issue tracker](https://github.com/JuliaPlots/Plots.jl/issues)... I don't know anything about plotting myself, so I'm not going to be able to help.

**Comment by mkborregaard** [comment]
I don't think Plots is going to give much attention to recipe errors without an MWE (given that there are 600 open tractable issues). I really hope to get time to look at this before my leave.

**Comment by richardreeve** [comment]
Yes, fair comment.
