### ISSUE TITLE
Extraneous linebreaks in `show` methods

### ISSUE THREAD

**Issue by jakobnissen** [richardreeve/Phylo.jl#69]
This is quite minor, but it looks like most objects in this package prints an extra newline in their `show` methods, i.e. the methods use `println`. Best practise is to use `print`, since the Julia REPL automatically inserts a newline after each object.

For example, a vector of nodes is printed like:
```julia
julia> collect(nodeiter(tree))[1:2]
2-element Vector{LinkNode{OneRoot, String, Dict{String, Any}, LinkBranch{OneRoot, String, Dict{String, Any}, Float64}}}:
 LinkNode A, a tip of the tree with an incoming connection (branch 4).

 LinkNode B, a tip of the tree with an incoming connection (branch 3).


julia>
```

**Comment by richardreeve** [comment]
Thanks @jakobnissen - this seems like an easy fix. I remember there being a problem a few years ago that vectors of phylogenetic elements were just appearing as an infinitely long line of unreadable text, but I guess that got changed?

**Comment by jakobnissen** [comment]
Looks like it, yes.

**Comment by richardreeve** [comment]
Finally fixed!
