### ISSUE TITLE
How can I rename the leaf nodes of a ::RootedTree?

### ISSUE THREAD

**Issue by casasgomezuribarri** [richardreeve/Phylo.jl#70]
I would like to rename all the leaves of my tree, of type `::RootedTree`. 

`setleafinfo!(mytree, vector)` throws the error 

```julia
ERROR: LoadError: MethodError: no method matching _setleafinfo!(::RootedTree, ::Vector{String})
Closest candidates are:
  _setleafinfo!(::Phylo.AbstractBranchTree, ::Any) at C:\Users\ivica\.julia\packages\Phylo\0WXtf\src\Tree.jl:68
  _setleafinfo!(::LinkTree{RT, NL, N, B, TD}, ::TD) where {RT, NL, N, B, TD} at C:\Users\ivica\.julia\packages\Phylo\0WXtf\src\LinkTree.jl:420
```
I couldn't find any information on the `::Phylo.AbstractBranchTree` type in the docs, but the [docstring of the function](http://docs.ecojulia.org/Phylo.jl/stable/man/attributes/#Phylo.setleafinfo!) suggests that the tree to be edited must be of type `::AbstractTree`. I tried `AbstractTree(mytree)`, but got the error

```julia
ERROR: MethodError: no method matching AbstractTree(::RootedTree)
```

Really, all I want to do is to plot my tree with a nicer format for the leaf names. How can I do it? (either editing the tree itself or specifying the names in the `plot` call)

**Comment by richardreeve** [comment]
`setleafinfo!()` is for setting the data associated with the tips / leaves of a tree rather than for renaming them. I don't remember ever creating a function to actually rename nodes because the idea is that the (internal and terminal) nodes are created with fixed names. How are you creating the tree originally so that it has the wrong tip names?

**Comment by mkborregaard** [comment]
You can e.g. read the tree from a Newick file and want to change the names from eg common to scientific names? This seems like a common use case to me.

**Comment by casasgomezuribarri** [comment]
Yup @mkborregaard that is exactly my case (well, species ID -weird format- to scientific species name). I didn't create the tree myself, and was expecting to be able to do everything I wanted to do with it in Julia (since it's the only language I know to a good level).

What about editing the plotting pane instead of the original tree?

How can the recipe in [plot.jl](https://github.com/EcoJulia/Phylo.jl/blob/dev/src/plot.jl) be changed so that there is an extra kwarg (`tips`?) that overwrites `getleafnames(tree)` in 


```julia
@recipe function f(tree::Phylo.AbstractTree; treetype = :dendrogram, marker_group = nothing, line_group = nothing, showtips = true, tipfont = (7,))

    linecolor --> :black
    grid --> false
    framestyle --> :none
    legend --> false
    colorbar --> true
    size --> (1000, 1000)

    d, h, n = _findxy(tree)
    adj = 0.03maximum(values(d))
    tipannotations = map(x->(d[x] + adj, h[x], x), getleafnames(tree))
....#continues
```

**Comment by mkborregaard** [comment]
You could just add a `tipnames = getleafnames(tree)` kwarg to the recipe function, and then use `tipnames` in line 14. Maybe add a check to ensure that the length of the iterable is correct. That is probably sensible under all circumstances, though the other use case sounds reasonable too.

**Comment by casasgomezuribarri** [comment]
Thanks for your help. I had never played with the source code of a package before, so it took me some time to realise what I was doing. I am quite behind schedule with other things right now so won't be submitting a PR (again, I've never done it before and can't really spare the time to learn that at the minute).

However, the following edit of /src/plot.jl worked for me:

```julia
using RecipesBase
using AxisArrays # need to ensure this package is loaded in the environment

@recipe function f(tree::Phylo.AbstractTree; tipnames = getleafnames(tree), treetype = :dendrogram, marker_group = nothing, line_group = nothing, showtips = true, tipfont = (7,)) # add extra kwarg 'tipnames'

    linecolor --> :black
    grid --> false
    framestyle --> :none
    legend --> false
    colorbar --> true
    size --> (1000, 1000)

    d, h, n = _findxy(tree)
    adj = 0.03maximum(values(d))

#################
    if length(tipnames) == length(getleafnames(tree))
        dict = Dict(getleafnames(tree) .=> string.(tipnames)) 
        tipannotations = map(x->(d[x] + adj, h[x], dict[x]), getleafnames(tree))
    else
        @warn "tipnames attribute must have $(length(getleafnames(tree))) elements. Using original tipnames instead."
        tipannotations = map(x->(d[x] + adj, h[x], x), getleafnames(tree))
    end
################
    lz = get(plotattributes, :line_z, nothing)
    #.... continues
```

Note: the part of the code wrapped in '###' is the only thing that is changed from the original file

**Comment by richardreeve** [comment]
Thanks @casasgomezuribarri / @mkborregaard - this seems like a useful thing to be able to do. I'm less certain about interactively changing the actually names of nodes (or branches) in the tree as that would disrupt a few things. In any event, maybe we should add this plotting functionality for now.

**Comment by richardreeve** [comment]
Okay, `renamenode!(tree, node, "new name")` now works for some tree types in #91 (including `RootedTree`) and allows you to rename any node including leaves. It'll return `true` if it succeeds (it may fail even for supported tree types if the new name is a duplicate), and `false` if it fails or the tree type is not supported. The new `RecursiveTree` types are able to rename nodes (so long as there is no leaf information, or it's a `Dict` (which includes `RootedTree`).
