### ISSUE TITLE
parsenexus() tree validation fails if '-' in TaxLabels

### ISSUE THREAD

**Issue by isaacovercast** [richardreeve/Phylo.jl#75]
Tested with Phylo.jl v0.4.21

When loading a nexus file, if any TaxLabels in the Taxa block contain dashes ('-') then the `open` operation will fail with the following messages:
```
┌ Warning: Taxa list length (6) and ntax (4) do not match
└ @ Phylo /home/isaac/.julia/packages/Phylo/0WXtf/src/newick.jl:436
┌ Info: Created a tree called "best"
└ @ Phylo /home/isaac/.julia/packages/Phylo/0WXtf/src/newick.jl:495
┌ Warning: Wrong number of roots for OneRoot tree (3)
└ @ Phylo /home/isaac/.julia/packages/Phylo/0WXtf/src/LinkTree.jl:223
Tree Tree does not validate!
```

Steps to reproduce:

Save the following file as `wat.nexus`:
```
#NEXUS
BEGIN TAXA;
      Dimensions NTax=4;
      TaxLabels fish-fry frog snake mouse;
END;

BEGIN TREES;
      Tree best=(fish, (frog, (snake, mouse)));
END;
```
In Julia REPL call: `ts = open(parsenexus, Phylo.path("wat.nexus"))`

**Comment by richardreeve** [comment]
Sorry @isaacovercast - I missed this when you posted it. I'll have a look at it as soon as I can. I've been trying to find the time to completely rewrite the parser because it's such a mess, but it's just so much work!

**Comment by isaacovercast** [comment]
Thanks for taking a look at it! No rush for me, I just edited the nex by hand.

**Comment by richardreeve** [comment]
Hi @isaacovercast - I realise this is long after you raised this issue, but I've just been looking at it, and I can't see any evidence that this is in fact legal nexus syntax. `-` is _punctuation_ according to the standard, and names of taxa have to be a single _word_ (and a word can only contain punctuation if it is enclosed in _'single quotes'_, which doesn't happen here). Beyond that, you're also not using the same word in the TAXA block as in the TREES block (_fish-fry_ vs _fish_). I've looked through the [original paper](https://academic.oup.com/sysbio/article/46/4/590/1629695), and it doesn't seem to allow any of that. Any thoughts?

**Comment by isaacovercast** [comment]
@richardreeve Thank you for sharing the original paper, fun to go back and read through it! I had no idea about the `-` punctuation specification, and I've probably just gotten used to other software which is more permissive (or less correct) in the treatment of `-` inside taxon labels. Thanks for clarifying, i'm happy to close this.
