### ISSUE TITLE
Plotting topology and big trees

### ISSUE THREAD

**Issue by mashu** [richardreeve/Phylo.jl#8]
Hi,
This is another feature that would be really useful. Plotting perhaps using plotly backend, so big trees can be viewed and zoom-ed in/out. I see there is show() function, but it does not show topology.
Being able to display tree, branches, how they are arranged, to immediately see the whole tree, just right away from the Julia code, is really nice for diagnostics. Maybe such function already exists ?

**Comment by richardreeve** [comment]
I'm afraid I don't have the requisite skills to do plotting, but you can use R's plotting functions if you like:

```julia
julia> using Phylo
INFO: Precompiling module Phylo.

julia> using RCall

julia> include(joinpath(Pkg.dir("Phylo"), "src/rcall.jl")) # Load in the helper code to interface to R
sexp (generic function with 103 methods)

julia> tree = rand(Ultrametric(10)) # Creates a random tree with 10 tips
Phylo.BinaryTree{Phylo.LeafInfo,Void} phylogenetic tree with 19 nodes and 18 branches
Leaf names:
String["tip 1", "tip 2", "tip 3", "tip 4", "tip 5", "tip 6", "tip 7", "tip 8", "tip 9", "tip 10"]

R> library(ape)

julia> @rput tree
Phylo.BinaryTree{Phylo.LeafInfo,Void} phylogenetic tree with 19 nodes and 18 branches
Leaf names:
String["tip 1", "tip 2", "tip 3", "tip 4", "tip 5", "tip 6", "tip 7", "tip 8", "tip 9", "tip 10"]

R> plot(tree)
```
You need to install R, the `ape` library in R (using `install.packages("ape")`) and the `RCall` package in Julia, so this isn't the simplest of solutions(!), but then you can use ape's plotting code. Note that you type `$` to switch from a Julia prompt to an R prompt, and hit the backspace key at the R prompt to switch back...

**Comment by mkborregaard** [comment]
I'll add plotting functionality at some point. I got a lot of the code ready.

**Comment by jangevaare** [comment]
Code from (here)[https://github.com/jangevaare/PhyloTrees.jl/blob/master/src/plot.jl] can be used/modified for this package as well @mkborregaard

**Comment by richardreeve** [comment]
That would be great, thanks. Apart from being a deeply inelegant solution, the R plotting I've been using isn't even very nice. I don't know if you've done much with trees, but the best tree plotting functionality I've seen is [ggtree](https://github.com/GuangchuangYu/ggtree) in case you're interested...

**Comment by mkborregaard** [comment]
Looks nice - can you saw what you like about it in particular? Just the fact that it can do a lot? I thought we'd start with the basics and build from there :-)

**Comment by richardreeve** [comment]
I've never used it in anger - I've never been much of a figure person - but I've had collaborators produce trees using it, and they do look good and the package is very flexible. I agree, basics first though!

However, looking at their code, I've liked the way it ties into the rest of that `ggplot2` ecosystem, so I guess that works from the `Plots.jl` perspective, assuming you were planning on going with that. The other thing is just the easy extensibility of it. For instance the simplicity of switching layouts:
```R
> library(ggtree)
ggtree v1.12.6  For help: https://guangchuangyu.github.io/software/ggtree

If you use ggtree in published research, please cite:
Guangchuang Yu, David Smith, Huachen Zhu, Yi Guan, Tommy Tsan-Yuk Lam. ggtree: an R package for visualization and annotation of phylogenetic trees with their covariates and other associated data. Methods in Ecology and Evolution 2017, 8(1):28-36, doi:10.1111/2041-210X.12628
> tr <- rtree(50)
> ggtree(tr)
> ggtree(tr, layout="slanted")
> ggtree(tr, layout="circular")
```
and so on. Not like some packages I've used in the past I guess...

**Comment by mkborregaard** [comment]
I was gonna implement dendrogram and fan to begin with, but it should def be that easy to switch

**Comment by mkborregaard** [comment]
Four years ago I wrote some pretty amazing code for this using BezierCurves for declaritive curves in Compose, too bad nobody cares about that anymore

**Comment by richardreeve** [comment]
Great - the simpler the better. Sounds good to me. As far as Compose is concerned, I didn't know about it before 10 seconds ago... it looks great - I always liked lisp :)
