### ISSUE TITLE
Tree saving available?

### ISSUE THREAD

**Issue by KYQiu21** [richardreeve/Phylo.jl#84]
Dear developers,

Thanks very much for this package. I am wondering if the current version supports saving/writing a tree.

Kaiyu

**Comment by mkborregaard** [comment]
It is not currently available to write a tree to a Newick file (only read), though you can always serialize your tree with JLSO (for future use in Julia). A Newick writer would be nice though.

**Comment by mkborregaard** [comment]
I guess a workaround is to use the R interface to write the tree.

**Comment by KYQiu21** [comment]
Thanks!

**Comment by richardreeve** [comment]
@KYQiu21 In fact, I'm beginning a full rewrite of the parser for reading newick / nexus files, and as part of that it's my intention to write a tree "writer" as well. I can currently parse the trees, but not actually input them, so I've got a bit of a way to go, but I hope to have time this month to complete this work.

**Comment by KYQiu21** [comment]
Thanks for your effort and look forward to a more powerful version, although it is already excellent 😉

**Comment by richardreeve** [comment]
Just to update here, I have been working on the parser, but I spotted some things that were slowing it down in the main code, and with the latest (0.5) release I can now read the largest supertree of plants that I'm aware of (31k tips) in 293ms rather than 23s (about 80x faster). Unfortunately this fix took some time (and may be lightly breaking for some people because I change the underlying tree structure to make type inference work, hence the 0.5 release) so I haven't made the progress I was hoping for on the main parser. I'm starting on that now.

**Comment by mkborregaard** [comment]
Just stating the obvious here: reading a 31k tips supertree in 293 ms (and building the corresponding representation in memory) in 293 ms is a pretty fantastic achievement. The plotting of that tree with this package would also be so much faster than R than even TTFP does not matter.

**Comment by KYQiu21** [comment]
Indeed!

**Comment by richardreeve** [comment]
Thanks. It's a nice thought, but I just tried benchmarking ape's `read.tree()`, and it's 86ms in RStudio (or perhaps unsurprisingly a faster 75ms using RCall and BenchmarkTools in Julia), so I've got a way to go still. Nonetheless, it's a lot closer!

To be fair they have been developing ape for over 20 years, and it's mostly written in C...

**Comment by richardreeve** [comment]
I just wish there was a decent parser generator for Julia. I've previously used yacc and bison in C, and it's just agonising handwriting them using the tools we currently have in Julia.

**Comment by mkborregaard** [comment]
Yeah this is something the biojulia people, e.g. @jakobnissen are also battling with (and improving).

**Comment by mkborregaard** [comment]
I think ape is faster because it doesn't build any internal representation - it's just two vectors of node links?

**Comment by richardreeve** [comment]
Yes. that does make things simpler, but I've now written a parser using [ParserCombinator.jl](https://github.com/andrewcooke/ParserCombinator.jl), and just parsing the 31k tip tree takes a few seconds without generating any structure sadly.

**Comment by richardreeve** [comment]
> Yeah this is something the biojulia people, e.g. @jakobnissen are also battling with (and improving).

Unfortunately they aren't though as far as I understand it, at least not in this context - BioJulia/Automa.jl#59 makes it clear they don't believe recursion is in scope, at least for the time being.
