### ISSUE TITLE
problem with outputnode function

### ISSUE THREAD

**Issue by HughMurrell** [richardreeve/Phylo.jl#95]
I am using Phylo v0.5.1 and when I list the nodes of a tree, the "internal node" and "leaf node" labels are interchanged.
Here is a minimal demonstration:

This input:

using Phylo
simpletree = parsenewick("(ant:17, (bat:31, cow:22):7, dog:22, (elk:33, fox:12):40);")
collect(Phylo.nodeiter(simpletree))

produced this output:

9-element Vector{RecursiveNode{OneRoot, String, Dict{String, Any}, Dict{String, Any}, PolytomousBranching, Float64}}:
 internal node 'ant'
 internal node 'bat'
 internal node 'cow'
 leaf node 'Node 4'
 internal node 'dog'
 internal node 'elk'
 internal node 'fox'
 leaf node 'Node 8'
 root node 'Node 9'

The "root node" label is correct but the "internal node" and "leaf node" labels are interchanged.

I think the problem is somewhere in show.jl in the src directory, probably with the outputnode function.

Also, the link to this issues page in your README is broken.

Thanks for all the good work,
Hugh Murrell

**Comment by richardreeve** [comment]
Thanks @HughMurrell - that's really easily fixed I hope (and sorry about the issues link!). I'm just going to merge it and release v0.5.2 now.
